#!/bin/bash
if [ -z "$1" ]
then
    echo ''
    echo "Usage: gg-apt-list-installed <filter>"
    echo "Use * filter to show all packages."
    echo ''
else 
    if [ "$1" = "*" ]
    then
        dpkg --get-selections | grep --color -i install
    else
        dpkg --get-selections | grep --color -i $1
    fi
fi