#!/bin/bash
function filter_warning {
    echo ''
    echo 'You can filter the list with: gg-apt-list-installed <filter>'
    echo ''
}

if [ -z "$1" ]; then
    filter_warning
    dpkg --get-selections | grep --color -i "[[:space:]]install"
    filter_warning
else
    dpkg --get-selections | grep --color -i "[[:space:]]install" | grep --color -i $1
fi