#!/bin/bash
if [ -z "$1" ]; then
    echo ''
    echo "Usage: gg-apt-list-available <filter>"
    echo "Use % filter to show all packages."
    echo ''
else 
    if [ $1 = "%" ]; then
        apt-cache pkgnames
    else
        apt-cache pkgnames | grep --color -i $1
    fi
fi