#!/bin/bash
function filter_warning {
    echo ''
    echo 'You can filter the list with: gg-apt-list-available <filter>'
    echo ''
}

if [ -z "$1" ]; then
    filter_warning
    apt-cache pkgnames
    filter_warning
else
    apt-cache pkgnames | grep --color -i $1
fi