#!/bin/bash
# Include gg-lib
. .gg-paths

function filter_warning {
    echo ''
    echo 'You can filter the list with: gg-fpm-pool-list <filter>'
    echo ''
}

if [ -z "$1" ]; then
    filter_warning
    ls $GG_FPM_POOLS
else
    ls $GG_FPM_POOLS | grep --color -i $1
fi