#!/bin/bash
# Include gg-lib
. .gg-lib
. .gg-paths

# Get current script location in $SCRIPT_PATH var
get_script_path

if [ -z "$1" ]; then
    echo ''
    echo "Usage: gg-fpm-pool-create <poolname>"
    echo "<poolname> should be the same as the username."
    echo ''
else 
    FILE="${GG_FPM_POOLS}/${1}.conf"
    sed -e "s;%POOLNAME%;$1;" $SCRIPT_PATH/templates/fpm-pool.tpl > $FILE
    $SCRIPT_PATH/gg-fpm restart
fi