#!/bin/bash
# Include gg-lib
. .gg-lib
. .gg-paths

# Get current script location in $SCRIPT_PATH var
get_script_path

if [ -z "$1" ]; then
    echo ''
    echo "Usage: gg-fpm-pool-delete <poolname>"
    echo "<poolname> should be the same as the username."
    echo ''
else 
    FILE="${GG_FPM_POOLS}/${1}.conf"

    if [ -f $FILE ]; then
        rm $FILE
        $SCRIPT_PATH/gg-fpm restart
    else
        echo ''
        echo "File ${FILE} not found!"
        echo ''
    fi
fi