#!/bin/bash
if [ -z "$1" ]; then
    echo ''
    echo "Usage: gg-group-list <filter>"
    echo "Use % filter to show all entries."
    echo ''
else 
    if [ $1 = "%" ]; then
        cut -d':' -f1 /etc/group
    else
        cut -d':' -f1 /etc/group | grep --color -i $1
    fi
fi