#!/bin/bash
# Include gg-lib
. .gg-paths

function filter_warning {
    echo ''
    echo 'You can filter the list with: gg-nginx-vhost-list-enabled <filter>'
    echo ''
}

if [ -z "$1" ]; then
    filter_warning
    ls $GG_NGINX_ENABLED
    echo ''
else
    ls $GG_NGINX_ENABLED | grep --color -i $1
fi