#!/bin/bash
# Include gg-lib
. .gg-paths

if [ -z "$1" ]; then
    echo ''
    echo "Usage: gg-nginx-vhost-list-available <filter>"
    echo "Use % filter to show all entries."
    echo ''
else 
    if [ $1 = "%" ]; then
        ls $GG_NGINX_AVAILABLE
    else
        ls $GG_NGINX_AVAILABLE | grep --color -i $1
    fi
fi