#!/bin/bash
# Include gg-lib
. .gg-lib

# Get current script location in $SCRIPT_PATH var
get_script_path

echo ''
prompt_yn "This will update your Galtzagorri installation, do you want to continue?"

# Update via GIT
git --work-tree=$SCRIPT_PATH --git-dir=$SCRIPT_PATH/.git pull
echo ''