#!/bin/bash
# Include gg-lib
. .gg-lib

if [ -z "$1" ]; then
    echo ''
    echo "Usage: gg-user-delete <username>"
    echo ''
else 
    echo ''
    echo 'WARNING! This will delete the user and the home directory.'
    echo "It will also delete the user group if it's empty."
    echo ''

    prompt_yn "Do you want to continue?"

    userdel -r $1
    crontab -r -u $1
fi