#!/bin/bash
function filter_warning {
    echo ''
    echo 'You can filter the list with: gg-user-list <filter>'
    echo ''
}

if [ -z "$1" ]; then
    filter_warning
    cut -d':' -f1 /etc/passwd
    filter_warning
else
    cut -d':' -f1 /etc/passwd | grep --color -i $1
fi